Only use last line as fileName when packing
0x80/isolate-package pull request #115
Opened 2024-11-25 18:25 UTC by hjellek

Fixes #114

2024-11-26 08:36 UTC, 0x80 commented on src/lib/utils/pack.ts
> +  const lastLine = stdout.trim().split("\n").pop() || "";
I think it would be better to throw a descriptive error if lastLine is undefined, don't you think? Maybe even add the stdout.trim() to the message, like `Failed to parse last line from stdout: ${stdout.trim()}`

If basename can't parse the empty string, or if fileName becomes an empty string, the resulting error might not be so obvious.

Also, I have a slight preference for `at(-1)` instead of `pop()`, but that's nitpicking :)

2024-11-26 08:38 UTC, 0x80 requested changes
See comment...

2024-11-26 09:08 UTC, hjellek commented on src/lib/utils/pack.ts
> +  const lastLine = stdout.trim().split("\n").pop() || "";
Agreed, updated now!

2024-11-26 12:39 UTC, 0x80 requested changes

2024-11-26 12:39 UTC, 0x80 commented on src/lib/utils/pack.ts
> +    throw new Error("Unable to find fileName from pack output");
I don't see a need to log and throw, as the thrown error message should appear anyway. 

Please throw message from log.error, as it is more informative.

2024-11-28 09:32 UTC, hjellek commented on src/lib/utils/pack.ts
> +    throw new Error("Unable to find fileName from pack output");
Not sure I understand exactly what you want me to do - only log, or only throw?

2024-11-28 15:27 UTC, 0x80 commented on src/lib/utils/pack.ts
> +    throw new Error("Unable to find fileName from pack output");
Only throw, but throw an error with the message that you currently use in log.error. Thanks!

2024-11-28 15:29 UTC, 0x80 commented on src/lib/utils/pack.ts
> +    throw new Error("Unable to find fileName from pack output");
... unless you can convince me that logging + throwing has a clear purpose. I never do that myself, but that doesn't mean I'm right necessarily ;)

2024-11-28 16:12 UTC, hjellek commented on src/lib/utils/pack.ts
> +    throw new Error("Unable to find fileName from pack output");
Gotcha, updated!

Well, I guess it depends on the error and log handling in general so I just did it both 😅
As you say, sometimes the error is shown to the user and the log message can contain more useful stuff for debugging.

2024-11-28 16:25 UTC, 0x80 approved these changes

2024-11-28 16:28 UTC, 0x80 commented on src/lib/utils/pack.ts
> +    throw new Error("Unable to find fileName from pack output");
Please run prettier (pnpm format) to make the checks pass, then I can merge it...

2024-11-28 16:31 UTC, hjellek commented on src/lib/utils/pack.ts
> +    throw new Error("Unable to find fileName from pack output");
Done!

And thank you for your swift response, and efforts on the library in general 😊

2024-11-28 17:01 UTC, merged

2024-11-28 17:06 UTC, 0x80 commented
@hjellek I've published it under @next. Maybe you can give it a try and confirm that it works for you? 

I will include it in firebase-tools-with-isolate when a new minor version of that the upstream firebase-tools comes out.

2024-11-28 19:08 UTC, hjellek commented
> @hjellek I've published it under @next. Maybe you can give it a try and confirm that it works for you?
> 

I'll be happy to test, but I can't find a branch or tag called `next` now?

2024-11-29 16:59 UTC, 0x80 commented
@hjellek It's available on npm under @next. So something like `pnpm add isolate-package@next -D` should work