Fix for Windows Git Bash w/ pnpm
0x80/isolate-package pull request #116
Opened 2024-12-13 01:04 UTC by jack1323

I want to say upfront that this tool is fantastic, and so is the typescript mono repo example.  I was able to finally restructure my mono-repo the way I've been hoping to and remove all my home-grown firebase publishing hacks.  

This PR addresses problems I had with "packages/common" in a Windows git bash environment using pnpm.  Naturally, both changes have to do with forward vs back slashes.

2024-12-14 08:35 UTC, 0x80 approved these changes
Thanks for you contribution! LGTM. I don't see an easy way to test this, so I'm just going to take your word for it ;)

2024-12-14 08:37 UTC, 0x80 requested changes
Please make sure the checks lint / formatting check succeeds

2024-12-16 21:29 UTC, jack1323 commented
lint & lint:format are now passing

2024-12-17 05:26 UTC, 0x80 approved these changes

2024-12-17 05:27 UTC, merged