Increase exec max buffer size to support large amounts of files
0x80/isolate-package pull request #18
Opened 2023-08-15 13:00 UTC by jieey1140

I'm going to build the nestjs app as isolate and use it in firebase deploy.

The following error occurs when executing isolation after nest build.

```
error RangeError: stderr maxBuffer length exceeded
    at new NodeError (node:internal/errors:372:5)
    at Socket.onChildStderr (node:child_process:485:14)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) 
  ``` 
     //   Below is the log I captured while debugging:

``` 
Error: Error: Error: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stderr maxBuffer length exceeded
    at pack (file:///Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/isolate-package@1.3.1/node_modules/isolate-package/src/utils/yaml.ts:15:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at processBuildOutputFiles (file:///Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/isolate-package@1.3.1/node_modules/isolate-package/src/index.ts:76:3)
    at start (file:///Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/isolate-package@1.3.1/node_modules/isolate-package/dist/index.mjs:768:3),[object Promise]
    at process.error (file:///Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/isolate-package@1.3.1/node_modules/isolate-package/src/utils/pack.ts:3:8)
    at process.emit (node:events:527:28)
    at process.emit (/Users/gimsehun/Documents/PROJECT-main/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
 ``` 
 
 
 We have identified that the excessive number of src files is causing issues, so we have increased the maxBuffer size in exec to accommodate repositories with a large number of files. (200KB(Default) -> 10MB)
 
 
 After making this change and conducting tests, we have confirmed that the (JavaScript compiled) environment now compiles successfully!

2023-08-15 14:04 UTC, 0x80 requested changes
Thanks for this PR 👍 One small change..

I will also change the title of the PR so it can be merged as a descriptive commit message.

2023-08-15 14:04 UTC, 0x80 commented on src/utils/pack.ts
> +  const execOption = {
Please rename this to execOptions.

2023-08-15 14:44 UTC, jieey1140 commented
@0x80  Thank you for the quick verification! 

I've reviewed the comment, and I agree that "options" seems better than "option." It has been updated :)

2023-08-15 15:02 UTC, jieey1140 commented
@0x80  Additional note: Thanks to the package you've created, we've been able to develop numerous common packages within our monorepo, resulting in a significant reduction of duplicated code. We wanted to take this opportunity to express our heartfelt gratitude! 👍

2023-08-15 18:37 UTC, 0x80 approved these changes

2023-08-15 18:41 UTC, 0x80 commented
@jieey1140 I'm happy to hear that people find it useful. 

My next step is to get it integrated into the official firebase-tools deploy command, as it allows for running the emulator still with changes hot reloading, but I'm a little swamped with other work so I don't know when I'll give that a try :)

2023-08-15 18:45 UTC, merged

2023-08-15 18:54 UTC, 0x80 commented
I have released version 1.3.3 with this change

2023-08-16 08:31 UTC, jieey1140 commented
@0x80  Thank you. I've verified that the build was successful without any errors. Have a great day!