Add basic support for Bun package manager
0x80/isolate-package pull request #99
Opened 2024-07-31 01:42 UTC by harveylee

Hello, I was able to successfully isolate and deploy a Firebase Functions project inside a Bun (v1.1.20) workspace by making these changes to `isolate-package`. The output lockfile falls back to NPM - which is fine for Firebase Functions, since I don't think Bun is supported anyway.

2024-08-01 14:15 UTC, 0x80 requested changes
Great to see that adding (partial) support was so easy. It seems like your editor didn't execute prettier on save, so please run the format script.

Also it would be great if you could add something to the readme 

> - Should work with any package manager, and tested with NPM, PNPM, and Yarn
  (both classic and modern)

2024-08-04 09:23 UTC, 0x80 approved these changes

2024-08-04 09:48 UTC, 0x80 commented
Thanks for your contribution. The formatting check still fails on the readme, but I'll fix that after merging. I will release an updated version soon.

2024-08-04 09:51 UTC, merged

2024-08-06 01:00 UTC, harveylee commented
Sorry I didn't realise there's linting on the readme! I'm a bit of an open source contribution novice.